2025-0205-01) 

CREATE OR REPLACE PROCEDURE proc_insert_buyprod(
    P_PROD_ID IN PROD.PROD_ID%TYPE, P_QTY IN NUMBER)
IS

BEGIN
    INSERT INTO BUYPROD VALUES (SYSDATE, P_PROD_ID, P_QTY);
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('오류발생 : '|| SQLERRM);
            ROLLBACK;
END;

(실행)

EXECUTE proc_insert_buyprod('P301000002', 10);

SELECT *
  FROM BUYPROD
 WHERE BUY_DATE=SYSDATE; 
 
 ACCEPT P_DAY PROMPT '일자 : '
 DECLARE
    L_DATE DATE := TO_DATE('&P_DAY');
 BEGIN
    proc_del_buyprod(L_DATE);
 END;
 
CREATE OR REPLACE PROCEDURE proc_del_buyprod(
   P_DATE DATE)
IS
BEGIN
    DELETE FROM BUYPROD WHERE BUY_DATE = P_DATE;
    COMMIT;
END;