2025-0109-01) 테이블 삭제명령
 - DROP TABLE 명령 사용
 (사용 형식)
  DROP TABLE 테이블명
  . 관계가 설정된 경우 자식테이블부터 삭제
  . 관계를 삭제한 후 테이블 삭제는 언제나 가능
  
사용예)
    DROP TABLE TEMP01;
    DROP TABLE TEMP02;
    DROP TABLE TEMP03;
    DROP TABLE TEMP04;
    DROP TABLE TEMP05;
    DROP TABLE TEMP06;
    DROP TABLE TEMP07;
    DROP TABLE TEMP08;
    DROP TABLE TEMP09;
    
    DROP TABLE ORDERS; 
    -- 관계제거
    ALTER TABLE ORDER_GOODS DROP CONSTRAINT FK_ORDER_ORDERS;
    ALTER TABLE ORDER_GOODS DROP CONSTRAINT FK_ORDER_GOODS;
    
    DROP TABLE GOODS;
    DROP TABLE ORDER_GOODS;
    DROP TABLE ORDERS;
    DROP TABLE CUST;