SELECT TO_CHAR(SYSDATE, 'CC"세기" BC Q"분기" ') FROM DUAL;

SELECT TO_CHAR(SYSDATE,' YYYY YYY YY Y YEAR') FROM DUAL;

SELECT TO_CHAR(SYSDATE,'YYYY-MONTH-MON-RM') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DAY - DY - D') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD - DDD - J') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD AM HH:MI:SS SSSSS') FROM DUAL;
