2025-0131-02)
CREATE [OR REPLACE] [UNIQUE | BITMAP] INDEX 인덱스명
    ON 테이블명(컬럼명 [, 컬럼명, ...] [ASC | DESC]);

SELECT EMPLOYEE_ID AS 사원번호,
       EMP_NAME AS 사원명,
       DEPARTMENT_ID AS 부서코드,
       HIRE_DATE AS 입사일,
       JOB_ID AS 직무코드
  FROM EMP
 WHERE EMP_NAME = 'TJ Olson';
 
 CREATE INDEX IDX_EMP ON EMP(EMP_NAME);
 
 SELECT MEM_ID, MEM_NAME, MEM_ADD1||' '||MEM_ADD2, MEM_MILEAGE
   FROM LYS00.MEMBER
  WHERE MEM_NAME = '오성순'; 
  
DROP INDEX LYS00.PK_MEM_ID;

CREATE INDEX LYS00.IDX_MEM_NAME ON LYS00.MEMBER(MEM_NAME);
COMMIT;


CREATE INDEX IDX_CART_NO ON CART(SUBSTR(CART_NO, 2, 6));
DROP INDEX IDX_CART_NO;

CREATE UNIQUE INDEX IDX_CART_NO ON CART(SUBSTR(CART_NO, 2, 6));







