CREATE TABLE HR.RETIRE AS 
	SELECT * FROM HR.EMPLOYEES;

COMMIT;

SELECT *
FROM (SELECT EMP_NAME, SALARY, HIRE_DATE
        FROM HR.EMP
       WHERE HIRE_DATE < TO_DATE('2020', 'YYYY')
       ORDER BY SALARY DESC)
WHERE ROWNUM < 11;


SELECT A.EMPLOYEE_ID, A.EMP_NAME, A.DEPARTMENT_ID
  FROM (SELECT EMPLOYEE_ID, EMP_NAME, DEPARTMENT_ID
          FROM HR.EMP
         WHERE HIRE_DATE < TO_DATE('20200101')
         ORDER BY SALARY DESC) A
 WHERE ROWNUM < 11;
 
 
DELETE FROM HR.EMP
WHERE EMPLOYEE_ID IN(SELECT A.EMPLOYEE_ID
                       FROM (SELECT EMPLOYEE_ID, EMP_NAME, DEPARTMENT_ID
                               FROM HR.EMP
                              WHERE HIRE_DATE < TO_DATE('20200101')
                              ORDER BY SALARY DESC) A
                      WHERE ROWNUM < 11);
                        
                              
CREATE OR REPLACE TRIGGER TG_RETIRE_EMP
    BEFORE DELETE ON HR.EMP
    FOR EACH ROW
  DECLARE
  BEGIN
    INSERT INTO RETIRE(EMPLOYEE_ID,EMP_NAME,DEPARTMENT_ID,RETIRE_DATE)
           VALUES(:OLD.EMPLOYEE_ID,:OLD.EMP_NAME,:OLD.DEPARTMENT_ID,SYSDATE);
    END;    
    
INSERT INTO LYS00.CART_PROD(CART_NO, PROD_ID, QTY)
    SELECT CART_NO, PROD_ID, CART_QTY
      FROM LYS00.CART
     WHERE CART_NO LIKE '202004%'
       AND CART_QTY >= 10;




SELECT PROD_ID,
       SUM(BUY_QTY) AS BSUM
  FROM LYS00.BUYPROD
 WHERE BUY_DATE BETWEEN TO_DATE('20200101') AND TO_DATE('20200131') 
 GROUP BY PROD_ID;
       
UPDATE LYS00.REMAIN A
   SET (A.REMAIN_I, A.REMAIN_J_99, A.REMAIN_DATE) =
       (SELECT A.REMAIN_I + B.BSUM, A.REMAIN_J_99 + B.BSUM, TO_DATE('20200201')
          FROM (SELECT PROD_ID,
                       SUM(BUY_QTY) AS BSUM
                  FROM LYS00.BUYPROD
                 WHERE BUY_DATE BETWEEN TO_DATE('20200101') AND TO_DATE('20200131') 
                 GROUP BY PROD_ID) B
         WHERE A.PROD_ID = B.PROD_ID);

SELECT * FROM LYS00.REMAIN;

ROLLBACK;
COMMIT;



















