UPDATE LYS00.REMAIN A
   SET (A.REMAIN_I, A.REMAIN_J_99, A.REMAIN_DATE) =
       (SELECT A.REMAIN_I + B.BSUM, A.REMAIN_J_99 + B.BSUM, TO_DATE('20200501')
          FROM (SELECT PROD_ID,
                       SUM(BUY_QTY) AS BSUM
                  FROM LYS00.BUYPROD
                 WHERE BUY_DATE BETWEEN TO_DATE('20200201') AND TO_DATE('20200430') 
                 GROUP BY PROD_ID) B
         WHERE A.PROD_ID = B.PROD_ID)
 WHERE A.PROD_ID IN (SELECT PROD_ID
                       FROM LYS00.BUYPROD
                      WHERE BUY_DATE BETWEEN TO_DATE('20200201') AND TO_DATE('20200430') 
                      GROUP BY PROD_ID);
 
SELECT * FROM LYS00.REMAIN;

ROLLBACK;
COMMIT;


-- DELETE FROM REMAIN;


--INSERT INTO REMAIN (REMAIN_YEAR, PROD_ID, REMAIN_J_00, REMAIN_J_99,REMAIN_DATE)
--SELECT '2020' , PROD_ID, PROD_PROPERSTOCK, PROD_PROPERSTOCK, TO_DATE('20200101')
--FROM LYS00.PROD;

--SELECT * FROM REMAIN;


SELECT PROD_ID,
       SUM(CART_QTY)
  FROM LYS00.CART
 WHERE SUBSTR(CART_NO, 1, 6) LIKE '202004%'
 GROUP BY PROD_ID;


SELECT F.PROD_ID, F.REMAIN_O + D.CSUM, F.REMAIN_J_99 - D.CSUM, TO_DATE('20200501') 
  FROM LYS00.REMAIN F
  LEFT JOIN (SELECT A.PROD_ID, NVL(C.BSUM, 0) AS CSUM
              FROM LYS00.PROD A
              LEFT JOIN (SELECT B.PROD_ID,
                                SUM(B.CART_QTY) AS BSUM
                           FROM LYS00.CART B
                          WHERE SUBSTR(CART_NO, 1, 6) LIKE '202004%'
                          GROUP BY B.PROD_ID) C ON(A.PROD_ID = C.PROD_ID)) D ON (D.PROD_ID = F.PROD_ID);
              

SELECT A.PROD_ID, NVL(C.BSUM, 0)
  FROM LYS00.PROD A
  LEFT JOIN (SELECT B.PROD_ID,
                    SUM(B.CART_QTY) AS BSUM
               FROM LYS00.CART B
              WHERE SUBSTR(CART_NO, 1, 6) LIKE '202004%'
              GROUP BY B.PROD_ID) C ON(A.PROD_ID = C.PROD_ID);     


UPDATE LYS00.REMAIN R
  SET (R.REMAIN_O, R.REMAIN_J_99, REMAIN_DATE)=
      (SELECT R.REMAIN_O+C.BSUM, R.REMAIN_J_99-C.BSUM, TO_DATE('20200501')
         FROM (SELECT A.PROD_ID AS APID, NVL(SUM(B.CART_QTY),0) AS BSUM
                 FROM LYS00.PROD A
                 LEFT JOIN LYS00.CART B ON(A.PROD_ID=B.PROD_ID AND B.CART_NO LIKE '202004%')
                GROUP BY A.PROD_ID) C
        WHERE R.PROD_ID=C.APID);         
        
        COMMIT;




























