CREATE OR REPLACE SYNONYM EMP FOR HR.EMPLOYEES;

CREATE OR REPLACE SYNONYM DEPT FOR HR.DEPARTMENTS;

SELECT * FROM DEPT;

-- 부서별 평균급여
SELECT DEPARTMENT_ID, ROUND(AVG(SALARY), 2)
  FROM EMP
 GROUP BY DEPARTMENT_ID;
 
SELECT A.EMPLOYEE_ID AS 사원번호,
       A.EMP_NAME AS 사원명,
       A.DEPARTMENT_ID AS 부서번호,
       B.DEPARTMENT_NAME AS 부서명,
       C.AVGS AS 부서평균급여,
       A.SALARY AS 급여
  FROM EMP A, DEPT B, (SELECT DEPARTMENT_ID, ROUND(AVG(SALARY), 2) AS AVGS
                         FROM EMP
                        GROUP BY DEPARTMENT_ID) C
 WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
   AND C.DEPARTMENT_ID = A.DEPARTMENT_ID
   AND A.SALARY > C.AVGS;
   