DECLARE
    L_CNT NUMBER:=0;
BEGIN
    LOOP
        L_CNT := L_CNT + 1;
        EXIT WHEN L_CNT > 9;
        DBMS_OUTPUT.PUT_LINE(6||' * '||L_CNT||' = '||L_CNT*6);
    END LOOP;
END;

DECLARE
    L_CNT NUMBER:=0;
BEGIN
    WHILE L_CNT < 9 LOOP
        L_CNT := L_CNT + 1;
        DBMS_OUTPUT.PUT_LINE(6||' * '||L_CNT||' = '||L_CNT*6);
    END LOOP;
END;

DECLARE
    
BEGIN
    FOR A IN 1..9 LOOP
        DBMS_OUTPUT.PUT_LINE(6||' * '||A||' = '||A*6);
    END LOOP;
END;




ACCEPT A_DID PROMPT '부서코드 : '
DECLARE 
    L_EID HR.EMPLOYEES.EMPLOYEE_ID%TYPE;
    L_ENAME VARCHAR2(100);
    L_DATE DATE;
    L_SALARY NUMBER:=0;
    
    CURSOR CUR_EMP01(P_DID HR.DEPARTMENTS.DEPARTMENT_ID%TYPE) IS
        SELECT EMPLOYEE_ID, EMP_NAME, HIRE_DATE, SALARY
          FROM HR.EMPLOYEES
         WHERE DEPARTMENT_ID = P_DID; 
BEGIN
    OPEN CUR_EMP01(&A_DID);
    LOOP
        FETCH CUR_EMP01 INTO L_EID, L_ENAME, L_DATE, L_SALARY;
            EXIT WHEN CUR_EMP01%NOTFOUND;
            DBMS_OUTPUT.PUT(L_EID||' ');
            DBMS_OUTPUT.PUT(RPAD(L_ENAME,30,' '));
            DBMS_OUTPUT.PUT(L_DATE||' ');
            DBMS_OUTPUT.PUT_LINE(TO_CHAR(L_SALARY,'99,999'));
            DBMS_OUTPUT.PUT_LINE('------------------------------------------------------');
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('총 인원 : '||CUR_EMP01%ROWCOUNT);
    CLOSE CUR_EMP01;
END;

(WHILE)
ACCEPT A_DID PROMPT '부서코드 : '
DECLARE 
    L_EID HR.EMPLOYEES.EMPLOYEE_ID%TYPE;
    L_ENAME VARCHAR2(100);
    L_DATE DATE;
    L_SALARY NUMBER:=0;
    
    CURSOR CUR_EMP01(P_DID HR.DEPARTMENTS.DEPARTMENT_ID%TYPE) IS
        SELECT EMPLOYEE_ID, EMP_NAME, HIRE_DATE, SALARY
          FROM HR.EMPLOYEES
         WHERE DEPARTMENT_ID = P_DID; 
BEGIN
    OPEN CUR_EMP01(&A_DID);
    FETCH CUR_EMP01 INTO L_EID, L_ENAME, L_DATE, L_SALARY;
    WHILE CUR_EMP01%FOUND LOOP
        DBMS_OUTPUT.PUT(L_EID||' ');
        DBMS_OUTPUT.PUT(RPAD(L_ENAME,30,' '));
        DBMS_OUTPUT.PUT(L_DATE||' ');
        DBMS_OUTPUT.PUT_LINE(TO_CHAR(L_SALARY,'99,999'));
        DBMS_OUTPUT.PUT_LINE('------------------------------------------------------');
        FETCH CUR_EMP01 INTO L_EID, L_ENAME, L_DATE, L_SALARY;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('총 인원 : '||CUR_EMP01%ROWCOUNT);
    CLOSE CUR_EMP01;
END;

(FOR)
ACCEPT A_DID PROMPT '부서코드 : '
DECLARE 
L_CNT NUMBER:= 0;
    CURSOR CUR_EMP01(P_DID HR.DEPARTMENTS.DEPARTMENT_ID%TYPE) IS
        SELECT EMPLOYEE_ID, EMP_NAME, HIRE_DATE, SALARY
          FROM HR.EMPLOYEES
         WHERE DEPARTMENT_ID = P_DID; 
BEGIN
    FOR REC IN CUR_EMP01(&A_DID)LOOP
        L_CNT := L_CNT + 1;
        DBMS_OUTPUT.PUT(REC.EMPLOYEE_ID||' ');
        DBMS_OUTPUT.PUT(RPAD(REC.EMP_NAME,30,' '));
        DBMS_OUTPUT.PUT(REC.HIRE_DATE||' ');
        DBMS_OUTPUT.PUT_LINE(TO_CHAR(REC.SALARY,'99,999'));
        DBMS_OUTPUT.PUT_LINE('------------------------------------------------------');
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('총 인원 : '||L_CNT);
END;


(INLINE SUBQEURY FOR)
ACCEPT A_DID PROMPT '부서코드 : '
DECLARE 
L_CNT NUMBER:= 0;
BEGIN
    FOR REC IN (SELECT EMPLOYEE_ID, EMP_NAME, HIRE_DATE, SALARY
                  FROM HR.EMPLOYEES
                 WHERE DEPARTMENT_ID=&A_DID) LOOP
        L_CNT := L_CNT + 1;
        DBMS_OUTPUT.PUT(REC.EMPLOYEE_ID||' ');
        DBMS_OUTPUT.PUT(RPAD(REC.EMP_NAME,30,' '));
        DBMS_OUTPUT.PUT(REC.HIRE_DATE||' ');
        DBMS_OUTPUT.PUT_LINE(TO_CHAR(REC.SALARY,'99,999'));
        DBMS_OUTPUT.PUT_LINE('------------------------------------------------------');
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('총 인원 : '||L_CNT);
END;


(LOOP)

DECLARE
    L_MID MEMBER.MEM_ID%TYPE;
    L_MNAME VARCHAR2(100);
    L_SUM NUMBER:=0;
    CURSOR CUR_CART02 IS
        SELECT MEM_ID, MEM_NAME
          FROM MEMBER
         WHERE MEM_ADD1 LIKE '충남%'; 
BEGIN
    OPEN CUR_CART02;
    LOOP
        FETCH CUR_CART02 INTO L_MID, L_MNAME;
        EXIT WHEN CUR_CART02%NOTFOUND;
        SELECT SUM(A.CART_QTY * B.PROD_PRICE) INTO L_SUM
          FROM CART A, PROD B
         WHERE A.PROD_ID = B.PROD_ID
           AND A.MEM_ID = L_MID
           AND SUBSTR(A.CART_NO, 1, 6) BETWEEN '202004' AND '202006';
        DBMS_OUTPUT.PUT(L_MID||'  ');
        DBMS_OUTPUT.PUT(RPAD(L_MNAME, 15));
        DBMS_OUTPUT.PUT_LINE(TO_CHAR(NVL(L_SUM, 0), '99,999,999'));
    END LOOP;
    CLOSE CUR_CART02;
END;

(WHILE)
DECLARE
    L_MID MEMBER.MEM_ID%TYPE;
    L_MNAME VARCHAR2(100);
    L_SUM NUMBER:=0;
    CURSOR CUR_CART02 IS
        SELECT MEM_ID, MEM_NAME
          FROM MEMBER
         WHERE MEM_ADD1 LIKE '충남%'; 
BEGIN
    OPEN CUR_CART02;
    FETCH CUR_CART02 INTO L_MID, L_MNAME;
    WHILE CUR_CART02%FOUND LOOP
        SELECT SUM(A.CART_QTY * B.PROD_PRICE) INTO L_SUM
          FROM CART A, PROD B
         WHERE A.PROD_ID = B.PROD_ID
           AND A.MEM_ID = L_MID
           AND SUBSTR(A.CART_NO, 1, 6) BETWEEN '202004' AND '202006';
        DBMS_OUTPUT.PUT(L_MID||'  ');
        DBMS_OUTPUT.PUT(RPAD(L_MNAME, 15));
        DBMS_OUTPUT.PUT_LINE(TO_CHAR(NVL(L_SUM, 0), '99,999,999'));
        FETCH CUR_CART02 INTO L_MID, L_MNAME;
    END LOOP;
    CLOSE CUR_CART02;
END;

(WHILE)
DECLARE
    L_SUM NUMBER:=0; 
BEGIN
    FOR L IN (SELECT MEM_ID, MEM_NAME
                FROM MEMBER
               WHERE MEM_ADD1 LIKE '충남%') LOOP
        SELECT SUM(A.CART_QTY * B.PROD_PRICE) INTO L_SUM
          FROM CART A, PROD B
         WHERE A.PROD_ID = B.PROD_ID
           AND A.MEM_ID = L.MEM_ID
           AND SUBSTR(A.CART_NO, 1, 6) BETWEEN '202004' AND '202006';
        DBMS_OUTPUT.PUT(L.MEM_ID||'  ');
        DBMS_OUTPUT.PUT(RPAD(L.MEM_NAME, 15));
        DBMS_OUTPUT.PUT_LINE(TO_CHAR(NVL(L_SUM, 0), '99,999,999'));
    END LOOP;
END;











