SELECT * FROM LYS00.LPROD;

SELECT * FROM HR.DEPARTMENTS
WHERE MANAGER_ID IS NOT NULL;

SELECT * FROM PRACTICE.CUST
ORDER BY CUST_NAME;

SELECT DISTINCT LPROD_GU FROM LYS00.PROD;

SELECT DISTINCT SUBSTR(MEM_ADD1,1,2) AS 주소
FROM LYS00.MEMBER
ORDER BY 주소;

SELECT MEM_ID AS 회원번호,
       MEM_NAME AS 회원명,
       MEM_ADD1||' '||MEM_ADD2 AS 주소,
       MEM_MILEAGE AS 마일리지
FROM LYS00.MEMBER
WHERE SUBSTR(MEM_REGNO2,1,1) IN ('2', '4')
ORDER BY MEM_MILEAGE DESC;

SELECT 5000*3 FROM DUAL;
