2025-0122-0)

월별,  회원별, 상품별 판매수량 합계
(GROUP BY절)
SELECT SUBSTR(CART_NO, 5, 2) AS 월,
       MEM_ID AS 회원번호,
       PROD_ID AS 상품번호, 
       SUM(CART_QTY) AS 판매수량합계
  FROM LYS00.CART
 WHERE CART_NO LIKE '2020%'
 GROUP BY SUBSTR(CART_NO, 5, 2), MEM_ID, PROD_ID
 ORDER BY 1,2,3;
 
(ROLLUP)
SELECT SUBSTR(CART_NO, 5, 2) AS 월,
       MEM_ID AS 회원번호,
       PROD_ID AS 상품번호, 
       SUM(CART_QTY) AS 판매수량합계
  FROM LYS00.CART
 WHERE CART_NO LIKE '2020%'
 GROUP BY ROLLUP(SUBSTR(CART_NO, 5, 2), MEM_ID, PROD_ID)
 ORDER BY 1,2,3;
 
 SELECT SUM(CART_QTY) 
   FROM LYS00.CART
  WHERE CART_NO LIKE '2020%';
  
(부분 ROLLUP)
SELECT SUBSTR(CART_NO, 5, 2) AS 월,
       MEM_ID AS 회원번호,
       PROD_ID AS 상품번호, 
       SUM(CART_QTY) AS 판매수량합계
  FROM LYS00.CART
 WHERE CART_NO LIKE '2020%'
 GROUP BY SUBSTR(CART_NO, 5, 2),ROLLUP(MEM_ID, PROD_ID)
 ORDER BY 1,2,3;