CREATE OR REPLACE PROCEDURE prod_del_cart(
    P_CARTNO CART_PROD.CART_NO%TYPE, P_PROD_ID PROD.PROD_ID%TYPE)
IS

BEGIN
    DELETE FROM CART_PROD
     WHERE CART_NO=P_CARTNO
       AND PROD_ID=P_PROD_ID;
    COMMIT;
    
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('오류발생 : '||SQLERRM);
            ROLLBACK;
END;


ACCEPT P_PROD_ID PROMPT '상품번호 : '
DECLARE 
    L_CART_NO CHAR(13);
    L_PROD_ID VARCHAR2(100);
BEGIN
    L_CART_NO := TO_CHAR(SUBSTR(&P_PROD_ID,1, 13));
    L_PROD_ID := SUBSTR(&P_PROD_ID,14, 23);
    prod_del_cart(L_CART_NO,L_PROD_ID);
END;

SELECT A.MEM_ID, A.MEM_MILEAGE, SUM(B.CART_QTY*PROD_PRICE)
  FROM MEMBER A, CART B, PROD C 
 WHERE A.MEM_ID=B.MEM_ID
   AND B.PROD_ID=C.PROD_ID
 GROUP BY A.MEM_ID, A.MEM_MILEAGE; 

SELECT D.MID,
    CASE D.DSUM
        WHEN D.DSUM BETWEEN 1000000 AND 5000000 THEN 500
        

SELECT A.MEM_ID AS MID, SUM(B.CART_QTY*PROD_PRICE) AS DSUM
  FROM MEMBER A, CART B, PROD C 
 WHERE A.MEM_ID=B.MEM_ID
   AND B.PROD_ID=C.PROD_ID
 GROUP BY A.MEM_ID, A.MEM_MILEAGE; 
 
 
 
CREATE OR REPLACE PROCEDURE proc_update_mem01(
    P_MEM_ID IN MEMBER.MEM_ID%TYPE,
    P_SUM_PRICE IN NUMBER,
    P_MEM_NAME OUT VARCHAR2,
    P_BMIL OUT NUMBER,
    P_AMIL OUT NUMBER
    )
IS
    L_AMIL NUMBER := 0;
BEGIN
    SELECT MEM_ID, MEM_MILEAGE
      INTO P_MEM_ID, P_BMIL
      FROM MEMBER
     WHERE MEM_ID=P_MEM_ID;
    
    
   
END;
    














