SELECT ABS(-100.5), ABS(0.0005) FROM DUAL;
SELECT SIGN(-100.5), SIGN(0.5), SIGN(0) FROM DUAL;
SELECT SQRT(16) FROM DUAL;
SELECT POWER(2, 10) FROM DUAL;

SELECT ROUND(23.5678, 2), ROUND(264362, -3) FROM DUAL;

SELECT MOD(15, 4) FROM DUAL;
SELECT FLOOR(109.9999), FLOOR(35), FLOOR(-109.999) FROM DUAL;
SELECT CEIL(109.9999), CEIL(35), CEIL(-109.999) FROM DUAL;

SELECT DEPARTMENT_ID AS 부서코드,
       ROUND(AVG(SALARY),1) AS 평균급여
  FROM HR.EMPLOYEES
 GROUP BY DEPARTMENT_ID;
 
 사용예) 회원테이블에서 회원들의 나이를 정확히 계산하시오
    ex ~년 ~개월
     두 날짜 자료 사이의 개월수 구하기 : MONTHS_BETWEEN(d1, d2)
     
SELECT MEM_ID AS 회원번호,
       MEM_NAME AS 회원명,
       MEM_BIR AS 생년월일
       ROUND(MONTHS_BETWEEN(SYSDATE, MEM_BIR)||'개월' AS 개월수,
       TRUNC(MONTHS_BETWEEN(SYSDATE, MEM_BIR)/12)||'년'||
       TO_CHAR(ROUND(MOD(MONTHS_BETWEEN(SYSDATE, MEM_BIR),12)), '00') ||'개월' AS 나이
  FROM LYS00.MEMBER;
   
SELECT MOD(29, 6), REMAINDER(29, 6), 
       MOD(26, 6), REMAINDER(26, 6)
  FROM DUAL;